Repository awslabs/fhir-works-on-aws-persistence-ddb, pull requests merged in 2021-04, with the labels that each got.

#61 fix: Only add customUserAgent when code is running on AWS, not when code is running locally
  src/AWS.ts
Labels: size/xs

#62 fix: don't overwrite meta param in Resource update/create
  .eslintrc.js
  .prettierrc.js
  package.json
  src/dataServices/dynamoDbBundleService.test.ts
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  yarn.lock
Labels: bug, size/m

#63 chore(release): 3.3.1
  CHANGELOG.md
  package.json
Labels: documentation, size/s

#65 fix: return the newly create meta field from bundle processer
  src/dataServices/dynamoDbBundleService.test.ts
  src/dataServices/dynamoDbBundleServiceHelper.ts
  testUtilities/GenerateStagingRequestsFactory.ts
Labels: bug, size/s

#67 chore(release): 3.3.2
  CHANGELOG.md
  package.json
Labels: documentation, size/xs

#68 fix: improve error logging for ddbToEs sync
  src/AWS.ts
  src/ddbToEs/ddbToEsHelper.ts
  src/ddbToEs/index.ts
Labels: enhancement, size/m

#70 chore(release): 3.3.3
  CHANGELOG.md
  package.json
Labels: documentation

#71 chore: add security scanning
  .github/workflows/codeql-analysis.yml
Labels: size/s
