Repository awslabs/fhir-works-on-aws-persistence-ddb, pull requests merged in 2021-07, with the labels that each got.

#92 chore(release): 3.6.0
  CHANGELOG.md
  package.json
Labels: size/xs

#94 fix: list bulk export files with tenant prefix
  src/bulkExport/bulkExport.test.ts
  src/bulkExport/bulkExport.ts
  src/dataServices/dynamoDbDataService.ts
Labels: size/s

#97 fix: change ES writes to use Bulk APIs
  src/ddbToEs/ESBulkCommand.ts
  src/ddbToEs/ddbToEsHelper.test.ts
  src/ddbToEs/ddbToEsHelper.ts
  src/ddbToEs/index.ts
  src/ddbToEs/promiseParamAndId.ts
Labels: enhancement, size/l
