Repository awslabs/fhir-works-on-aws-persistence-ddb, pull requests merged in 2021-09, with the labels that each got.

#110 chore: normalize all the line endings
  .github/PULL_REQUEST_TEMPLATE.md
  .github/no-response.yaml
  .npmignore
  .npmrc
  THIRD-PARTY
  src/constants.ts
  src/dataServices/__mocks__/dynamoDbBundleService.ts
  src/dataServices/__mocks__/dynamoDbDataService.ts
  src/dataServices/documentStatus.ts
  src/dataServices/dynamoDb.ts
  src/dataServices/dynamoDbBundleService.test.ts
  src/dataServices/dynamoDbBundleServiceHelper.test.ts
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbHelper.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
  src/dataServices/dynamoDbUtil.test.ts
  src/dataServices/dynamoDbUtil.ts
  src/index.ts
  src/objectStorageService/__mocks__/s3ObjectStorageService.ts
  src/objectStorageService/objectStorageInterface.ts
  src/objectStorageService/s3.ts
  src/objectStorageService/s3DataService.test.ts
  src/objectStorageService/s3DataService.ts
  src/objectStorageService/s3ObjectStorageService.ts
  testUtilities/regExpressions.ts
Labels: size/xl

#112 fix: bulk export return the correct content-type
  src/bulkExport/bulkExport.ts
Labels: bug, size/xs

#113 chore(release): 3.8.1
  CHANGELOG.md
  package.json
Labels: documentation, size/xs

#115 chore: resolve transitive dependency on set-value
  package.json
  yarn.lock
Labels: size/s

#120 chore: pin elasticsearch client version
  package.json
  yarn.lock
Labels: size/s

#121 chore(release): 3.8.2
  CHANGELOG.md
  package.json
Labels: size/xs
