Repository awslabs/fhir-works-on-aws-persistence-ddb, pull requests merged in 2021-06, with the labels that each got.

#82 chore(release): 3.4.0
  CHANGELOG.md
  package.json
Labels: size/s

#83 feat: add alias for new and existing index
  package.json
  src/ddbToEs/ddbToEsHelper.test.ts
  src/ddbToEs/ddbToEsHelper.ts
  src/ddbToEs/index.ts
  yarn.lock
Labels: size/m

#85 chore(release): 3.4.1
  CHANGELOG.md
  package.json
Labels: size/xs

#87 feat: Add multi tenancy to S3
  src/objectStorageService/__mocks__/s3ObjectStorageService.ts
  src/objectStorageService/s3.ts
  src/objectStorageService/s3DataService.test.ts
  src/objectStorageService/s3DataService.ts
  src/objectStorageService/s3ObjectStorageService.ts
Labels: size/m

#86 feat: tenant isolation for DDB CRUD operations
  src/constants.ts
  src/dataServices/dynamoDbBundleService.ts
  src/dataServices/dynamoDbBundleServiceHelper.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbHelper.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
  src/dataServices/dynamoDbUtil.test.ts
  src/dataServices/dynamoDbUtil.ts
Labels: size/m

#91 feat: update ddbToEs to handle multi-tenant records
  src/ddbToEs/ddbToEsHelper.ts
  src/ddbToEs/index.ts
Labels: size/s

#90 feat: Multi tenancy bulk export
  src/bulkExport/bulkExport.test.ts
  src/bulkExport/bulkExport.ts
  src/bulkExport/getJobStatus.test.ts
  src/bulkExport/getJobStatus.ts
  src/bulkExport/startExportJob.test.ts
  src/bulkExport/startExportJob.ts
  src/bulkExport/stopExportJob.test.ts
  src/bulkExport/stopExportJob.ts
  src/bulkExport/types.ts
  src/bulkExport/updateStatus.test.ts
  src/bulkExport/updateStatus.ts
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
Labels: size/l
