Repository awslabs/fhir-works-on-aws-persistence-ddb, pull requests merged in 2021-08, with the labels that each got.

#98 feat: persistence change for group export
  src/bulkExport/bulkExport.ts
  src/bulkExport/startExportJob.ts
  src/bulkExport/types.ts
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
Labels: size/m

#99 chore(release): 3.6.1
  CHANGELOG.md
  package.json
Labels: documentation, size/xs

#100 feat: enable hard delete in Elasticsearch
  src/ddbToEs/ddbToEsHelper.test.ts
  src/ddbToEs/ddbToEsHelper.ts
  src/ddbToEs/index.ts
Labels: size/s

#101 fix: lint issue
  src/dataServices/dynamoDbParamBuilder.ts
  src/ddbToEs/ddbToEsHelper.ts
Labels: size/xs

#103 chore: dependency fix
  package.json
  yarn.lock
Labels: size/s

#106 feat: implement multi-tenancy and group export
  package.json
  src/bulkExport/bulkExport.test.ts
  src/bulkExport/bulkExport.ts
  src/bulkExport/getJobStatus.test.ts
  src/bulkExport/getJobStatus.ts
  src/bulkExport/startExportJob.test.ts
  src/bulkExport/startExportJob.ts
  src/bulkExport/stopExportJob.test.ts
  src/bulkExport/stopExportJob.ts
  src/bulkExport/types.ts
  src/bulkExport/updateStatus.test.ts
  src/bulkExport/updateStatus.ts
  src/constants.ts
  src/dataServices/dynamoDbBundleService.ts
  src/dataServices/dynamoDbBundleServiceHelper.ts
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbHelper.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
  src/dataServices/dynamoDbUtil.test.ts
  src/dataServices/dynamoDbUtil.ts
  src/ddbToEs/ddbToEsHelper.test.ts
  src/ddbToEs/ddbToEsHelper.ts
  src/ddbToEs/index.ts
  src/objectStorageService/__mocks__/s3ObjectStorageService.ts
  src/objectStorageService/s3.ts
  src/objectStorageService/s3DataService.test.ts
  src/objectStorageService/s3DataService.ts
  src/objectStorageService/s3ObjectStorageService.ts
  yarn.lock
Labels: size/xl

#107 chore(release): 3.7.0
  CHANGELOG.md
  package.json
Labels: size/xs

#108 feat: add config options to DdbToEsSync
  src/ddbToEs/ddbToEsHelper.test.ts
  src/ddbToEs/ddbToEsHelper.ts
  src/ddbToEs/ddbToEsSync.test.ts
  src/ddbToEs/ddbToEsSync.ts
  src/ddbToEs/index.ts
  src/index.ts
Labels: size/l

#109 chore(release): 3.8.0
  CHANGELOG.md
  package.json
Labels: size/s
