Repository awslabs/fhir-works-on-aws-persistence-ddb, pull requests merged in 2021-05, with the labels that each got.

#77 refactor: add customized logger
  package.json
  src/bulkExport/stopExportJob.ts
  src/dataServices/dynamoDbBundleService.ts
  src/ddbToEs/ddbToEsHelper.ts
  src/ddbToEs/index.ts
  src/loggerBuilder.ts
  src/objectStorageService/s3ObjectStorageService.ts
  yarn.lock
Labels: size/m

#78 chore(release): 3.3.4
  CHANGELOG.md
  package.json
Labels: size/xs

#76 chore: adding GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/miscellaneous.md
Labels: size/s

#79 fix: initialize ES client only once
  src/ddbToEs/index.ts
Labels: size/xs
