Repository awslabs/fhir-works-on-aws-persistence-ddb, pull requests merged in 2022-03, with the labels that each got.

#138 feat: add support for FHIR Subscriptions
  package.json
  src/dataServices/__mocks__/dynamoDbDataService.ts
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
  src/dataServices/dynamoDbUtil.test.ts
  src/dataServices/dynamoDbUtil.ts
  src/objectStorageService/s3DataService.ts
  yarn.lock
Labels: size/m

#141 chore(release): 3.10.0
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr

#142 fix: fix update query for Subscriptions
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
Labels: size/s

#143 chore(release): 3.10.1
  CHANGELOG.md
  package.json
Labels: size/xs, auto-release-pr
