Repository awslabs/fhir-works-on-aws-persistence-ddb, pull requests merged in 2022-01, with the labels that each got.

#129 chore: add unit test coverage and enforcement
  .github/workflows/code-coverage.yml
  codecov.yml
  package.json
Labels: size/s

#131 feat: implement getActiveSubscriptions
  src/dataServices/dynamoDbDataService.test.ts
  src/dataServices/dynamoDbDataService.ts
  src/dataServices/dynamoDbParamBuilder.test.ts
  src/dataServices/dynamoDbParamBuilder.ts
  src/dataServices/dynamoDbUtil.test.ts
  src/dataServices/dynamoDbUtil.ts
  src/objectStorageService/s3DataService.ts
Labels: size/m

#134 docs: Update README to specify that deployment package depends on this package, not vice versa
  README.md
Labels: size/xs
